#define DOLLAR                          1
#define NUMERIC                         2
#define DOLLAR_CURLY                    3
#define CURLY                           4
#define IDENTIFIER                      5
#define REGEX                           6
#define SHELL                           7
#define CHAR                            8
#define COLON                           9
