#define DOLLAR                          1
#define NUMERIC                         2
#define DOLLAR_CURLY                    3
#define CURLY                           4
#define IDENTIFIER                      5
#define COLON                           6
#define SHELL                           7
#define REGEXY                          8
#define CHAR                            9
